@baseURL = https://whatsapp-automation-pm0i.onrender.com

### see server running
GET {{baseURL}}

### set sender
POST {{baseURL}}/set-sender

### send message
POST {{baseURL}}/send-message
Content-Type: application/json

{
    "message": "Hello, World!"
}

### send message with line breaks (\n> )
POST {{baseURL}}/send-message
Content-Type: application/json

{
    "message": "here are your late busses:\n> bcm123\n> bcm321\n> bcm213\n\nhere are your delayed busses:\n> bcm123\n> bcm321\n> bcm213\n\nhere are your cancelled busses:\n> bcm123\n> bcm321\n> bcm213\n"
}