services:
  - type: web
    name: whatsapp-puppeteer
    runtime: docker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
    disk:
      name: user-data
      mountPath: /usr/src/app/user-data
      sizeGB: 1
